### ISSUE TITLE
undefined method `new' for "Rack::RawUpload":String 

### ISSUE THREAD

**Issue by ugifractal** [New-Bamboo/rack-raw-upload#25]
When running on ruby 2.5.1 and rails 5.2
starting rails got: 
```
/Users/sugiarto/.rvm/gems/ruby-2.5.1@ruby251rails52/gems/actionpack-5.2.0/lib/action_dispatch/middleware/stack.rb:38:in `build': undefined method `new' for "Rack::RawUpload":String (NoMethodError)
```

I think the documentation for rails 5.2 need to be added from 
```
config.middleware.use 'Rack::RawUpload'
```

become

```
config.middleware.use Rack::RawUpload
```
thanks
sugiarto

**Comment by pablobm** [comment]
Thank you for raising this. Memory fails me, but I guess using a string must have been common practice long time ago. Updated now.
